name: Docker CD

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: docker.pkg.github.com
          repository: cantalo/cantalo/cantalo
          tag_with_ref: true